token: "Your Bot Token"
chatId: "The channel you want minecraft chat messages to be sent to. Leave blank to disable."
storageType: 0 # 0 = Skript Variabls, 1 = YML File (Do not change this after people have already started linking.)